### ISSUE TITLE
Dependencies aren't pulled in automatically

### ISSUE THREAD

**Issue by AeroNotix** [Ralt/lxc-wrapper#2]
Also builds using a specific quicklisp tree. I think we could do something similar to Lispkit where we build in a local environment (mainly due to the fact we're building a binary).

**Comment by ralt** [comment]
Meh honestly I'd rather have people familiar with lisp compiling, and others using the binaries.

Now of course, I wouldn't say no to some kind of virtualenv for python. I'd like to have a dedicated tool instead of a hack in make though...

**Comment by AeroNotix** [comment]
That's a nice to have, then.

But a target to call the necessary `(ql:quickload :foo)`'s would be nice ?

**Comment by ralt** [comment]
Fixed in https://github.com/Ralt/lxc-wrapper/commit/3f0177e6341d4aa9d5dac8c7614e3bd24a71a18d
